In [ ]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# define example
data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
values = array(data)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)

In [1]:
from sklearn.preprocessing import LabelEncoder

In [7]:
from numpy import array

In [8]:
data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
values = array(data)
print(values)

['cold' 'cold' 'warm' 'cold' 'hot' 'hot' 'warm' 'cold' 'warm' 'hot']


In [3]:
from sklearn.preprocessing import OneHotEncoder

In [11]:
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)

[0 0 2 0 1 1 2 0 2 1]


In [12]:
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [16]:
# invert first example
from numpy import argmax
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[2, :])])
print(inverted)

['warm']


/home/kamran/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [22]:
#from numpy import array
#from numpy import argmax
#from keras.utils import to_categorical
# define example
#data = [1, 3, 2, 0, 3, 2, 2, 1, 0, 1]
#data = array(data)
#print(data)
# one hot encode
#encoded = to_categorical(data)
#print(encoded)
# invert encoding
#inverted = argmax(encoded[0])
#print(inverted)

In [18]:
import pandas as pd

In [19]:
df = {'age':['m', 'f', 'm', 'f']}

In [20]:
df = pd.DataFrame(df)

In [21]:
df.head()

age
0   m
1   f
2   m
3   f

In [24]:
#Convert to Lable Encode
# integer encode
label_encoder = LabelEncoder()
df['age'] = label_encoder.fit_transform(df.age)
print(df['age'])

0    1
1    0
2    1
3    0
Name: age, dtype: int64


In [25]:
df.age

0    1
1    0
2    1
3    0
Name: age, dtype: int64

In [28]:
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
df['age'] = integer_encoded.reshape(len(df['age']), 1)
onehot_encoded = onehot_encoder.fit_transform(df['age'])
print(onehot_encoded)

ValueError: Expected 2D array, got 1D array instead:
array=[1. 0. 1. 0.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.